manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: crehmann
      url-base: https://github.com/crehmann
    - name: hunterwei
      url-base: https://github.com/hunterwei
  projects:
    - name: zmk
      remote: hunterwei
      revision: tps42_wip
      import: app/west.yml
  self:
    path: config
